In [12]:
!git clone 'https://github.com/Lorenz92/SKADC1.git'
% cd SKADC1
!echo $PWD

Cloning into 'SKADC1'...
remote: Enumerating objects: 41, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 41 (delta 17), reused 25 (delta 6), pack-reused 0
Unpacking objects: 100% (41/41), done.


In [2]:
import pandas as pd
import numpy as np
import requests
import matplotlib.pyplot as plt
import sys
from astropy.io import fits
import os

import src.dataset as dataset
import src.config as config
from src.utils import *
import src.preprocessing as prep

# from src.config import * 

%load_ext autoreload
%autoreload 2

np.random.seed(config.RANDOM_SEED)

In [7]:
for download_info in config.required_files:
    if not os.path.exists(os.path.join(config.TRAIN_DATA_FOLDER, download_info['file_name'])):
        download_data(download_info['file_name'], download_info['url'], config.DOWNLOAD_FOLDER)

Download completed!
Download completed!


In [3]:
# Dataset parsing and loading
# use "subset" to load a small portion of data for development/debugging purposes

ska_dataset = dataset.SKADataset(train_set_path=config.TRAIN_SET_PATH, subset=config.DATA_SUBSET)
print(ska_dataset.raw_train_df.shape)
ska_dataset.raw_train_df.head()

(19222, 15)


ID  RA (core)  DEC (core)  RA (centroid)  DEC (centroid)      FLUX  \
0  24121695  -0.642227  -29.775242      -0.642316      -29.775211  0.000035   
1  20167150  -0.390473  -29.867493      -0.390667      -29.868851  0.029555   
2  20045120  -0.021411  -29.643486      -0.021359      -29.643561  0.000653   
3  33938384  -0.316375  -29.697647      -0.316375      -29.697647  0.000017   
4   7527248  -0.336528  -29.627335      -0.336527      -29.627338  0.000054   

   Core frac     BMAJ    BMIN       PA  SIZE  CLASS  SELECTION          x  \
0   0.000000    5.600   5.551  328.554     1      1          1  19704.519   
1   0.016924  107.110  43.263  191.258     1      1          1  18401.338   
2   0.012185    5.037   3.525  276.587     1      1          1  16493.600   
3   0.000000    0.847   0.266  346.641     2      1          1  18020.319   
4   0.044763    3.343   1.515  279.006     1      1          1  18125.824   

           y  
0  17712.942  
1  17160.919  
2  18506.577  
3  18182.095  
4  18600.680

In [4]:
data_560Mhz_1000h_fits = fits.open('./data/training/560Mhz_1000h.fits')
# data_560Mhz_1000h_fits.info()
data_560Mhz_1000h_fits.filename()

# print(data_560Mhz_1000h_fits[0].data)
# print(data_560Mhz_1000h_fits[0].data.shape)

data_560Mhz_1000h = data_560Mhz_1000h_fits[0].data[0,0]


In [28]:
# Visualization test
from astropy.io import fits
from astropy.utils.data import download_file

# image_file = download_file('https://owncloud.ia2.inaf.it/index.php/s/hbasFhd4YILNkCr/download', cache=True )

# image_data = fits.getdata(image_file)
# image_data = image_data.reshape(image_data.shape[2:])

# compute per value to clip the image
perc = 99.9
percentileThresh = np.percentile(data_560Mhz_1000h, perc)
print (f'{perc} percentile {percentileThresh}')

# # crop the image to speed up computation and clip using per value
# image_crop= image_data[5000:10000, 5000:10000]
# image_crop.clip(max=percentileThresh)

# plt.figure(figsize=(100, 100))
# # plt.imshow(normalized_data, cmap='viridis', vmax=255, vmin=0)
# for idx in range(25):
#     plt.subplot(5, 5, idx+1)
#     plt.axis('off')
#     base = 200 * idx
#     end = base + 200
#     normalized_data = image_crop[base:end, base:end] * (1.0 / percentileThresh)
#     plt.imshow(normalized_data, cmap='viridis', vmax=1, vmin=0)

99.9 percentile 8.316711500810925e-06


### Preprocessing

In [5]:
coords = ska_dataset._convert_boxes_to_px_coord(ska_dataset.raw_train_df, data_560Mhz_1000h_fits[0].header)

In [6]:
pd.DataFrame.from_dict(coords)

x1            y1            x2            y2  major_semia_px  \
0      19699.889820  17708.334874  19709.135520  17717.543623        4.633850   
1      18314.128617  17121.775102  18488.540079  17200.059688       88.630651   
2      16490.663037  18502.418816  16496.536575  18510.726749        4.167982   
3      18019.631633  18181.823147  18020.999232  18182.360119        0.700870   
4      18124.509296  18597.936034  18127.132703  18603.414392        2.766243   
...             ...           ...           ...           ...             ...   
19217  17592.572752  16742.936603  17593.009233  16743.428821        0.319405   
19218  18658.822580  18666.464880  18659.100383  18666.968994        0.276376   
19219  17523.170058  16995.697610  17523.352636  16995.761662        0.093504   
19220  16950.523810  17747.923087  16950.979337  17748.452311        0.264791   
19221  18166.845099  19812.685038  18167.336911  19813.128832        0.248242   

       minor_semia_px  pa_in_rad       width     height  
0            4.593304   5.734349    9.245699   9.208748  
1           35.798972   3.338082  174.411463  78.284586  
2            2.916843   4.827354    5.873538   8.307933  
3            0.220108   6.050027    1.367598   0.536972  
4            1.253622   4.869573    2.623407   5.478358  
...               ...        ...         ...        ...  
19217        0.078610   0.853117    0.436482   0.492218  
19218        0.080265   1.127797    0.277803   0.504113  
19219        0.024824  -0.226387    0.182578   0.064053  
19220        0.227555  -1.498732    0.455528   0.529224  
19221        0.219280  -0.296287    0.491812   0.443793  

[19222 rows x 9 columns]

In [7]:
df_train = ska_dataset._extend_dataframe(ska_dataset.raw_train_df, coords)
df_train.head()

ID  RA (core)  DEC (core)  RA (centroid)  DEC (centroid)      FLUX  \
0  24121695  -0.642227  -29.775242      -0.642316      -29.775211  0.000035   
1  20167150  -0.390473  -29.867493      -0.390667      -29.868851  0.029555   
2  20045120  -0.021411  -29.643486      -0.021359      -29.643561  0.000653   
3  33938384  -0.316375  -29.697647      -0.316375      -29.697647  0.000017   
4   7527248  -0.336528  -29.627335      -0.336527      -29.627338  0.000054   

   Core frac     BMAJ    BMIN       PA  ...          y            x1  \
0   0.000000    5.600   5.551  328.554  ...  17712.942  19699.889820   
1   0.016924  107.110  43.263  191.258  ...  17160.919  18314.128617   
2   0.012185    5.037   3.525  276.587  ...  18506.577  16490.663037   
3   0.000000    0.847   0.266  346.641  ...  18182.095  18019.631633   
4   0.044763    3.343   1.515  279.006  ...  18600.680  18124.509296   

             y1            x2            y2  major_semia_px  minor_semia_px  \
0  17708.334874  19709.135520  17717.543623        4.633850        4.593304   
1  17121.775102  18488.540079  17200.059688       88.630651       35.798972   
2  18502.418816  16496.536575  18510.726749        4.167982        2.916843   
3  18181.823147  18020.999232  18182.360119        0.700870        0.220108   
4  18597.936034  18127.132703  18603.414392        2.766243        1.253622   

   pa_in_rad       width     height  
0   5.734349    9.245699   9.208748  
1   3.338082  174.411463  78.284586  
2   4.827354    5.873538   8.307933  
3   6.050027    1.367598   0.536972  
4   4.869573    2.623407   5.478358  

[5 rows x 24 columns]

In [24]:
x1_min = int(np.floor(min(df_train['x1'])))
y1_min = int(np.floor(min(df_train['y1'])))

x2_max = int(np.floor(max(df_train['x2'])))
y2_max = int(np.floor(max(df_train['y2'])))

data_560Mhz_1000h_train = data_560Mhz_1000h[y1_min:y2_max, x1_min:x2_max]
data_560Mhz_1000h_train.shape


(3187, 3491)

In [25]:
fits_max_data_560Mhz_1000h = np.max(data_560Mhz_1000h)
print(fits_max_data_560Mhz_1000h)

data_560Mhz_1000h_train_clipped = np.clip(data_560Mhz_1000h_train, a_min=0, a_max=fits_max_data_560Mhz_1000h)

0.48094657


In [26]:
data_560Mhz_1000h_train_clipped

array([[0.0000000e+00, 5.0277004e-07, 8.1352823e-07, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 4.7234460e-07, 7.5504875e-07, ..., 0.0000000e+00,
        0.0000000e+00, 1.5155882e-07],
       [0.0000000e+00, 0.0000000e+00, 4.7753889e-07, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [0.0000000e+00, 3.2216460e-07, 2.1111914e-07, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        4.3899996e-07, 6.1143220e-07]], dtype=float32)

In [32]:
patches={}
patches = ska_dataset._split_in_patch(data_560Mhz_1000h_train_clipped, df_train, data_560Mhz_1000h_fits.filename(), x1_min, y1_min, config.TRAIN_PATCHES_FOLDER, 205) # Remember to remove internal limit

[[0.0000000e+00 5.0277004e-07 8.1352823e-07 ... 2.1992520e-07
  3.3757752e-07 8.9618879e-08]
 [0.0000000e+00 4.7234460e-07 7.5504875e-07 ... 0.0000000e+00
  2.7678368e-08 3.8842813e-08]
 [0.0000000e+00 0.0000000e+00 4.7753889e-07 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 ...
 [1.6627402e-07 2.2166087e-07 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.3635220e-07 2.9386493e-07 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]]
image saved


In [33]:
a = np.load(os.path.join(config.TRAIN_PATCHES_FOLDER, 'your_file.npy'))
print(a)

[[0.0000000e+00 5.0277004e-07 8.1352823e-07 ... 2.1992520e-07
  3.3757752e-07 8.9618879e-08]
 [0.0000000e+00 4.7234460e-07 7.5504875e-07 ... 0.0000000e+00
  2.7678368e-08 3.8842813e-08]
 [0.0000000e+00 0.0000000e+00 4.7753889e-07 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 ...
 [1.6627402e-07 2.2166087e-07 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [1.3635220e-07 2.9386493e-07 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  0.0000000e+00 0.0000000e+00]]


#TODO:
- Ingrandire bbox
- unire bbox sovrapposte
- Mergiare branch data_clean (anche alla fine)
- Quando vengono create le patch, ritagliare le bbox per farle stare tutte nella patch X
- Check tra nostro dataset pulito e quello di ICRAR (dopo aver mergiato il branch data_clean)

Da capire per la rete:
- bisogna scalre input tra 0 e 255 intero?
- salvare le patch come immagini o possiamo darle in input on the fly?
- è necessario un custom input layer che converte le nostra immagini da 1 a 3 canali?

In [5]:
# Download VGG16 weights
# 'https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5'

download_data('vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5', 
'https://github.com/fchollet/deep-learning-models/releases/download/v0.1/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5', config.MODEL_WEIGHTS + '/vgg16')


Download completed!


In [8]:
# First net version
import keras
from keras import backend as K
from keras.layers import Input, Conv2D, MaxPooling2D, Reshape, Concatenate

FROZEN_LAYERS_IDX = [1, 2, 4, 5]
ANCHOR_NUM = 6
PROB_PRED_OUT = 2 * ANCHOR_NUM
COORD_PRED_OUT = 4 * ANCHOR_NUM 
input_shape=(600, 600, 1) #TODO: change to 205,205,1

vgg16_weight_path = os.path.join('./model/vgg16/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5')

# Add custom input-layer to change from1 to 3 channels
inp = Input(input_shape)
expander_layer = Conv2D(filters=3, kernel_size=(1, 1), padding='same', activation='relu', name='Custom_input_layer')(inp)

'''
# Load pretrained VGG16 and remove last MaxPool layer
# VGG16 = keras.applications.VGG16(include_top=False, weights="imagenet", pooling=None) # Commentato perchè non siamo riusciti a togliere l'ultimo layer
# x = x(expander_layer)
'''

# Block 1
x = Conv2D(64, (3, 3), activation='relu', padding='same', name='block1_conv1', trainable=False)(expander_layer)
x = Conv2D(64, (3, 3), activation='relu', padding='same', name='block1_conv2', trainable=False)(x)
x = MaxPooling2D((2, 2), strides=(2, 2), name='block1_pool')(x)

# Block 2
x = Conv2D(128, (3, 3), activation='relu', padding='same', name='block2_conv1', trainable=False)(x)
x = Conv2D(128, (3, 3), activation='relu', padding='same', name='block2_conv2', trainable=False)(x)
x = MaxPooling2D((2, 2), strides=(2, 2), name='block2_pool')(x)

# Block 3
x = Conv2D(256, (3, 3), activation='relu', padding='same', name='block3_conv1')(x)
x = Conv2D(256, (3, 3), activation='relu', padding='same', name='block3_conv2')(x)
x = Conv2D(256, (3, 3), activation='relu', padding='same', name='block3_conv3')(x)
x = MaxPooling2D((2, 2), strides=(2, 2), name='block3_pool')(x)

# Block 4
x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block4_conv1')(x)
x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block4_conv2')(x)
x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block4_conv3')(x)
x = MaxPooling2D((2, 2), strides=(2, 2), name='block4_pool')(x)

# Block 5
x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv1')(x)
x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv2')(x)
x = Conv2D(512, (3, 3), activation='relu', padding='same', name='block5_conv3')(x)
# x = MaxPooling2D((2, 2), strides=(2, 2), name='block5_pool')(x)

print(x)


# # Freeze first 4 convolutional layers
# for idx in FROZEN_LAYERS_IDX:
#   VGG16.layers[idx].trainable = False

# # Create Region Proposal Net
x = Conv2D(filters=512, kernel_size=(3, 3), padding='same', activation='relu', name='18_RPN_Conv1')(x)
cls_pred = Conv2D(filters=PROB_PRED_OUT, kernel_size=(1, 1), padding='same', activation='sigmoid', name='19_Anchor_Cls_Conv')(x) #output of layer 20
reg_pred = Conv2D(filters=COORD_PRED_OUT, kernel_size=(1, 1), padding='same', activation='linear', name='19_Anchor_Reg_Conv')(x) #output of layer 19

print(x)
print(cls_pred.shape)
print(reg_pred.shape)

anch_target_cls = Reshape((cls_pred.shape[1]**2, cls_pred.shape[3]), name='20_Anchor_Target_cls')(cls_pred)
anch_target_reg = Reshape((reg_pred.shape[1]**2, reg_pred.shape[3]), name='20_Anchor_Target_reg')(reg_pred)

print(anch_target_cls)
print(anch_target_reg)

region_prop_net = keras.Model(inp, [cls_pred, reg_pred], name='Region Proposal')

region_prop_net.load_weights(vgg16_weight_path, by_name=True)

# region_prop_net.compile(loss='categorical_crossentropy', optimizer='adam')

region_prop_net.summary()

KerasTensor(type_spec=TensorSpec(shape=(None, 37, 37, 512), dtype=tf.float32, name=None), name='block5_conv3/Relu:0', description="created by layer 'block5_conv3'")
KerasTensor(type_spec=TensorSpec(shape=(None, 37, 37, 512), dtype=tf.float32, name=None), name='18_RPN_Conv1/Relu:0', description="created by layer '18_RPN_Conv1'")
(None, 37, 37, 12)
(None, 37, 37, 24)
KerasTensor(type_spec=TensorSpec(shape=(None, 1369, 12), dtype=tf.float32, name=None), name='20_Anchor_Target_cls/Reshape:0', description="created by layer '20_Anchor_Target_cls'")
KerasTensor(type_spec=TensorSpec(shape=(None, 1369, 24), dtype=tf.float32, name=None), name='20_Anchor_Target_reg/Reshape:0', description="created by layer '20_Anchor_Target_reg'")
Model: "Region Proposal"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_6 (InputLayer)            [(None, 600, 60

In [ ]:
def rpn_loss_regr(num_anchors):
    """Loss function for rpn regression
    Args:
        num_anchors: number of anchors (9 in here)
    Returns:
        Smooth L1 loss function 
                           0.5*x*x (if x_abs < 1)
                           x_abx - 0.5 (otherwise)
    """
    def rpn_loss_regr_fixed_num(y_true, y_pred):

        # x is the difference between true value and predicted value
        x = y_true[:, :, :, 4 * num_anchors:] - y_pred

        # absolute value of x
        x_abs = K.abs(x)

        # If x_abs <= 1.0, x_bool = 1
        x_bool = K.cast(K.less_equal(x_abs, 1.0), tf.float32)

        return lambda_rpn_regr * K.sum(
            y_true[:, :, :, :4 * num_anchors] * (x_bool * (0.5 * x * x) + (1 - x_bool) * (x_abs - 0.5))) / K.sum(epsilon + y_true[:, :, :, :4 * num_anchors])

    return rpn_loss_regr_fixed_num

In [115]:
y_rpn_regr = np.zeros((3, 3, 3 * 4))
y_rpn_regr[0] = 9
y_rpn_regr[1] = 1
y_rpn_regr

array([[[9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.],
        [9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [116]:
y_rpn_regr = np.transpose(y_rpn_regr, (2, 0, 1))
print(y_rpn_regr)

[[[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]

 [[9. 9. 9.]
  [1. 1. 1.]
  [0. 0. 0.]]]


In [117]:
y_rpn_regr = np.expand_dims(y_rpn_regr, axis=0)
print(y_rpn_regr)

[[[[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]

  [[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]

  [[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]

  [[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]

  [[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]

  [[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]

  [[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]

  [[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]

  [[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]

  [[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]

  [[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]

  [[9. 9. 9.]
   [1. 1. 1.]
   [0. 0. 0.]]]]


In [14]:
y_rpn_regr.shape

NameError: name 'y_rpn_regr' is not defined

In [ ]:
a,b,c = prep.calc_rpn(df_train.head(1), 600, 600,600, 600)

Error: connect ECONNREFUSED 127.0.0.1:63301

TODO - 20210502:
- creare colonne per coordinate bbox nel sistema di riferimento della patch
- creare cartelle per patches con jpeg + pkl delle sue sole bbox
- ragionare su dimensioni patch
X Caricare pesi VGG16 nel nuovo network
- lanciare training

In [ ]:
#TODO: Provare YOLO che ad Asperti piace
# Ablation study
# Provare, a parità di frequenza, le esposizioni diverse come canali